### ISSUE TITLE
Add repos

### ISSUE THREAD

**Issue by lDucks** [BattlePlugins/BattlePipelineLib#1]
Add..
- [x] BattleCore
- [x] BattleTracker
- [x] BattleScoreboardAPI
- [x] BattleWebAPI
- [x] MCApi
- [x] ArenaSpleef
- [x] ArenaParkour
- [x] ArenaCTF

Maybe..
- [ ] Blutonium
- [ ] Dac
- [ ] Futbol 
- [ ] Plunger

**Comment by Redned235** [comment]
Blutonium, Dac, Futbol and Plunger were ones @Europia79 added. I'm not sure if we're going to officially update them or not; I think he had some kind of plans there.

**Comment by lDucks** [comment]
done
